AspNetMvcBlog/Blog.Web.Mvc/Controllers/AuthController.cs
using Blog.Business.Dtos;
using Blog.Business.Services;
using Blog.Business.Services.Abstract;
using Blog.Web.Mvc.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace Blog.Web.Mvc.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _us;

        public AuthController(IUserService us) {
            _us = us;
        }

        public IActionResult Register() => View();

        [HttpPost]
        public IActionResult Register(RegisterViewModel model)
        {
            if (HttpContext.User.Identity.IsAuthenticated) return Redirect("/");
            if (ModelState.IsValid) {
                _us.Insert(new UserDto { Name = model.Name, Email = model.Email, Password = model.Password, Phone = model.Phone != null ? model.Phone : "", City = model.City !=null?model.City: "" });
                return RedirectToAction(nameof(Login));
            }
            else { 
                return View(model);
            }
        }


        public IActionResult Login() => View();

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (HttpContext.User.Identity.IsAuthenticated) return Redirect("/");
            
            if (ModelState.IsValid)
            {
                var user =_us.GetByEmailPassword(model.Email,model.Password);
                if(user != null)
                {
                    var props = new AuthenticationProperties() { /*ExpiresUtc = DateTime.UtcNow.AddMinutes(60),*/
                        IsPersistent = true
                    };

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,_us.ConvertToPrincipal(user),props);
                    if (!user.Roles.IsNullOrEmpty() && user.Roles.Contains("Admin")) return Redirect("/Admin/Home");
                    return Redirect("/");
                }
                else {
                    ViewBag.Error = "E-Mail veya şifre yanlış";
                        }
            }

                return View(model);
        }
        
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return Redirect("/");
        }

        public IActionResult ForgotPassword()
        {
            return View();
        }
    }
}

AspNetMvcBlog/Blog.Web.Mvc/Controllers/BlogController.cs
using Blog.Business.Dtos;
using Blog.Business.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blog.Web.Mvc.Controllers
{
    public class BlogController : Controller
    {
        private readonly PostService _ps;

        public BlogController(PostService ps)
        {
            _ps = ps;
        }

        public IActionResult Search(string query ="s", int page = 1)
        {
            var posts = _ps.GetAll();
                //.Where(e => e.Title.Contains(query));
                //.Skip((page - 1) * 10).Take(10);

            var list = new List<PostDto>();

            foreach (PostDto post in posts) {
                if (post.Title.Contains(query))
                {
                    list.Add(post);
                }
            }

            ViewBag.Query = query;

            return View(list);
        }

        //[Route("/blog/title-slug")]
        public IActionResult Detail(int id)
        {
            var post = _ps.GetById(id);
           if (post == null) { 
            return RedirectToAction("Index","Home");
            }
            return View(post);
        }
    }
}

AspNetMvcBlog/Blog.Web.Mvc/Views/Shared/Components/Navbar/Default.cshtml
<!--Header Starts-->
@using Blog.Data.Entity
@model NavbarDto
<header class="header-top bg-grey justify-content-center">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-2 col-md-4 text-center d-none d-lg-block">
				<a class="navbar-brand " asp-controller="Home" asp-action="Index">
					<img src="/images/logo.png" alt="" class="img-fluid">
				</a>
			</div>
			<div class="col-lg-10 col-md-12">
				<nav class="navbar navbar-expand-lg navigation-2 navigation">
					<a class="navbar-brand text-uppercase d-lg-none" asp-controller="Home" asp-action="Index">
						<img src="/images/logo.png" alt="" class="img-fluid">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
						<span class="ti-menu"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbar-collapse">
						<ul id="menu" class="menu navbar-nav mx-auto">
							<li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link">Anasayfa</a></li>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Kategoriler
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown2">
									@foreach (CategoryDto c in Model.categories)
									{
										<a class="dropdown-item" asp-route="CategorySlug" asp-route-slug="@c.Slug">@c.Name</a>
									}
								</div>
							</li>
							@* pageleri service ekleyip burayı aç *@
							@foreach(PageDto p in Model.pages){
							<li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link">@p.Title</a></li>
							}
							
						</ul>
						
						<ul class="list-inline mb-0 d-block d-lg-none">
							<li class="list-inline-item"><a href="#"><i class="ti-facebook"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="ti-twitter"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="ti-linkedin"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="ti-pinterest"></i></a></li>
						</ul>
						
					</div>
					<div class="text-right search d-none d-lg-block">
						<div class="search_toggle"><i class="ti-search"></i></div>
					</div>


					@if (!Context.User.Identity.IsAuthenticated)
					{
						<ul class="list-inline mb-0">
							<li class="list-inline-item"><a asp-controller="auth" asp-action="register">Register</a></li>
							<li class="list-inline-item"><a asp-controller="auth" asp-action="login">Login</a></li>
						</ul>
					}
					else
					{
						<ul class="menu navbar-nav mx-auto">

							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									@Context.User.Identity.Name
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown2">
									@if (Context.User.IsInRole("Admin"))
									{
										<a class="dropdown-item" asp asp-area="admin">Admin Page</a>
									}
									<a class="dropdown-item" asp-controller="Auth" asp-action="logout">Logout</a>
									
								</div>
							</li>

						</ul>
					}

				</nav>
			</div>
			
		</div>
	</div>
</header>
<div class="search-wrap">
	<div class="overlay">
		<form asp-controller="Blog" asp-action="Search" class="search-form">
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-9">
						<input type="text" class="form-control" placeholder="Search..." name="query">
					</div>
					<div class="col-md-2 col-3 text-right">
						<div class="search_toggle toggle-wrap d-inline-block">
							<i class="ti-close"></i>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
<!--Header Ends-->