AspNetMvcBlog/Blog.Web.Mvc/Controllers/CategoryController.cs
using Blog.Business.Services;
using Blog.Business.Dtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Blog.Business.Services.Abstract;

namespace Blog.Web.Mvc.Controllers
{
    public class CategoryController : Controller
    {
        private readonly PostService _ps;
        private readonly ICategoryService _categoryService;

        public CategoryController(PostService ps, ICategoryService cs)
        {
            _ps = ps;
            _categoryService = cs;
        }

        // /category/index/1
        // /category/software
        [Route("/category/{slug}", Name = "CategorySlug")]
        public IActionResult Index(string slug, int page = 1)
        {
            var posts = _ps.GetAll()
                .Where(e => e.CategoryDtos.Any(e => e.Slug == slug))
                .Skip((page - 1) * 10).Take(10)
                .ToList();

            var category = _categoryService.GetBySlug(slug);
            ViewBag.CategoryName = category.Name;

            return View(posts);
        }
    }
}

AspNetMvcBlog/Blog.Web.Mvc/ViewComponents/NavbarViewComponent.cs
using Blog.Business.Services;
using Blog.Business.Services.Abstract;
using Blog.Data;
using Blog.Data.Entity;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Mvc.ViewComponents;

public class NavbarViewComponent : ViewComponent
{
	private readonly ICategoryService _cs;
	private readonly PageService _pageService;

	public NavbarViewComponent(ICategoryService cs,PageService pageService)
	{
		_cs = cs;
		_pageService = pageService;
	}

	public async Task<IViewComponentResult> InvokeAsync()
	{
		//AppDbContext Db;
		//db = Db;

		return View(
			new NavbarDto
			{
				categories = _cs.GetAll(),
				pages = _pageService.GetAll()
			}
			);
		//return View();
	}
}

AspNetMvcBlog/Blog.Web.Mvc/Views/Shared/Search.cshtml
<div class="text-right search d-none d-lg-block">
	<div class="search_toggle"><i class="ti-search"></i></div>
</div>

<!--search overlay start-->
<div class="search-wrap">
	<div class="overlay">
		<form action="#" class="search-form">
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-9">
						<input type="text" class="form-control" placeholder="Search..." />
					</div>
					<div class="col-md-2 col-3 text-right">
						<div class="search_toggle toggle-wrap d-inline-block">
							<i class="ti-close"></i>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

AspNetMvcBlog/Blog.Web.Mvc/Views/Shared/_Article.cshtml
<!--Content Starts-->
<section class="section-padding">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="row">
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="/images/news/f1.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class="cat-name text-color font-extra text-sm text-uppercase letter-spacing-1">Explore</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">The best place to explore to enjoy</a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">June 15, 2019</span>
						</article>
					</div>
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="/images/news/f2.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Lifestyle</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">How to Make list for travelling alone</a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">September 15, 2019</span>
						</article>
					</div>
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="/images/news/f3.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class=" cat-name text-color font-sm font-extra text-uppercase letter-spacing">Food</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">5 ingredient cilantro vinaigrette</a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">September 15, 2019</span>
						</article>
					</div>
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="/images/news/f4.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Explore</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">A Simple Way to Feel Like Home When You Travel</a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">March 20, 2019</span>
						</article>
					</div>
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="/images/news/f5.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Travel</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">What Type of Traveller Are You?</a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">September 15, 2019</span>
						</article>
					</div>
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="/images/news/f6.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Experience</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">A Road Trip Review of the 2018</a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">July 10, 2019</span>
						</article>
					</div>
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="/images/news/f7.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class=" cat-name text-color font-sm font-extra text-uppercase letter-spacing">music</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">Portugal’s Sunset summer vission</a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">September 15, 2019</span>
						</article>
					</div>
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="/images/news/f8.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">beauty</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">The best soft Tropical Getaway</a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">March 12, 2019</span>
						</article>
					</div>
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="~/images/news/f9.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Travel</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">Memoriable Paris Girls Trip </a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">April 19, 2019</span>
						</article>
					</div>
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="~/images/news/f10.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Experience</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">How to Plan your Trip the Right Way</a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">February 15, 2019</span>
						</article>
					</div>
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="/images/news/f11.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Travel</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">8 Powerful Ways to Add Vibrant Colour to Your Life</a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">August 15, 2019</span>
						</article>
					</div>
					<div class="col-lg-3 col-md-6">
						<article class="post-grid mb-5">
							<a class="post-thumb mb-4 d-block" href="blog-single.html">
								<img src="/images/news/f12.jpg" alt="" class="img-fluid w-100">
							</a>
							<span class=" cat-name text-color font-sm font-extra text-uppercase letter-spacing">Lifestyle</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">The best to-do list to help boost your productivity</a></h3>
							<span class="text-muted letter-spacing text-uppercase font-sm">October 2, 2019</span>
						</article>
					</div>
				</div>
			</div>
			<div class="m-auto">
				<div class="pagination mt-5 pt-4">
					<ul class="list-inline ">
						<li class="list-inline-item"><a href="#" class="active">1</a></li>
						<li class="list-inline-item"><a href="#">2</a></li>
						<li class="list-inline-item"><a href="#">3</a></li>
						<li class="list-inline-item"><a href="#" class="prev-posts"><i class="ti-arrow-right"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>
<!--Content Ends-->

AspNetMvcBlog/Blog.Web.Mvc/Views/Shared/_Footer.cshtml
<div class="footer-btm mt-5 pt-4 border-top">
    <div class="row">
        <div class="col-lg-12">
            <ul class="list-inline footer-socials-2 text-center">
                <li class="list-inline-item"><a href="#">Privacy policy</a></li>
                <li class="list-inline-item"><a href="#">Support</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Contact</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Category</a></li>
            </ul>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="copyright text-center ">
                &copy; @DateTime.Now.Year all rights reserved to <a href="https://themefisher.com/">themefisher.com</a>
            </div>

        </div>
    </div>
</div>
       

AspNetMvcBlog/Blog.Web.Mvc/Views/Shared/_Header.cshtml
<!--Header Starts-->
<header class="header-top bg-grey justify-content-center">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-2 col-md-4 text-center d-none d-lg-block">
				<a class="navbar-brand " asp-controller="Home" asp-action="Index">
					<img src="/images/logo.png" alt="" class="img-fluid">
				</a>
			</div>
			<div class="col-lg-8 col-md-12">
				<nav class="navbar navbar-expand-lg navigation-2 navigation">
					<a class="navbar-brand text-uppercase d-lg-none" asp-controller="Home" asp-action="Index">
						<img src="/images/logo.png" alt="" class="img-fluid">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
						<span class="ti-menu"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbar-collapse">
						<ul id="menu" class="menu navbar-nav mx-auto">
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" asp-controller="Home" asp-action="Index" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Home
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown">
									<a class="dropdown-item" asp-controller="Home" asp-action="Index">Home 1</a>
									<a class="dropdown-item" href="index-2.html">Home 2</a>
									<a class="dropdown-item" href="index-3.html">Home 3</a>
									<a class="dropdown-item" href="index-4.html">Home 4</a>
									<a class="dropdown-item" href="index-5.html">Home 5</a>
									<a class="dropdown-item" href="index-6.html">Home 6</a>
								</div>
							</li>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Blog Posts
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown2">
									<a class="dropdown-item" href="standard-fullwidth.html">Standard Fullwidth</a>
									<a class="dropdown-item" href="standard-left-sidebar.html">Standard Left Sidebar</a>
									<a class="dropdown-item" href="standard-right-sidebar.html">Standard Right Sidebar</a>
								</div>
							</li>
							<li class="nav-item"><a href="about.html" class="nav-link">About</a></li>
							<li class="nav-item"><a asp-controller="Category" asp-action="Index" class="nav-link">Category</a></li>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Post Format
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown3">
									<a class="dropdown-item" href="post-video.html">Video Formats</a>
									<a class="dropdown-item" href="post-audio.html">Audio Format</a>
									<a class="dropdown-item" href="post-link.html">Quote Format</a>
									<a class="dropdown-item" href="post-gallery.html">Gallery Format</a>
									<a class="dropdown-item" href="post-image.html">Image Format</a>
								</div>
							</li>
							<li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
						</ul>
						<ul class="list-inline mb-0 d-block d-lg-none">
							<li class="list-inline-item"><a href="#"><i class="ti-facebook"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="ti-twitter"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="ti-linkedin"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="ti-pinterest"></i></a></li>
						</ul>
					</div>
				</nav>
			</div>
			<div class="col-lg-2 col-md-4 col-6">
				<div class="header-socials-2 text-right d-none d-lg-block">
					<ul class="list-inline mb-0">
						<li class="list-inline-item"><a href="#"><i class="ti-facebook"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-twitter"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-linkedin"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-pinterest"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</header>
<!--Header Ends-->

AspNetMvcBlog/Blog.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Revolve - Personal Magazine blog Template</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Favicon-->
    <link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">
    <!-- THEME CSS
    ================================================== -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="/plugins/bootstrap/css/bootstrap.min.css">
    <!-- Themify -->
    <link rel="stylesheet" href="/plugins/themify/css/themify-icons.css">
    <link rel="stylesheet" href="/plugins/slick-carousel/slick-theme.css">
    <link rel="stylesheet" href="/plugins/slick-carousel/slick.css">
    <!-- Slick Carousel -->
    <link rel="stylesheet" href="/plugins/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="/plugins/owl-carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="/plugins/magnific-popup/magnific-popup.css">
    <!-- manin stylesheet -->
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
    @*@Html.Partial("_Header")*@
    @await Component.InvokeAsync("Navbar")

    @RenderBody()

    <section class="footer-2 section-padding gray-bg pb-5">
        <div class="container">
            @Html.Partial("_Subscribe")
            @Html.Partial("_Footer")
        </div>
    </section>
    
    <!-- THEME JAVASCRIPT FILES
    ================================================== -->
    <!-- initialize jQuery Library -->
    <script src="/plugins/jquery/jquery.js"></script>
    <!-- Bootstrap jQuery -->
    <script src="/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/plugins/bootstrap/js/popper.min.js"></script>
    <!-- Owl caeousel -->
    <script src="/plugins/owl-carousel/owl.carousel.min.js"></script>
    <script src="/plugins/slick-carousel/slick.min.js"></script>
    <script src="/plugins/magnific-popup/magnific-popup.js"></script>
    <!-- Instagram Feed Js -->
    <script src="/plugins/instafeed-js/instafeed.min.js"></script>
    <!-- Google Map -->
    <script src="/maps/api/js_key_AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw.js"></script>
    <script src="/plugins/google-map/gmap.js"></script>
    <!-- main js -->
    <script src="/js/custom.js"></script>
</body>
</html>

AspNetMvcBlog/Blog.Web.Mvc/Views/Shared/_Slider.cshtml
<!--Slider Starts-->
<section class="slider mt-4">
	<div class="container-fluid">
		<div class="row no-gutters">
			<div class="col-lg-12 col-sm-12 col-md-12 slider-wrap">
				<div class="slider-item">
					<div class="slider-item-content">
						<div class="post-thumb mb-4">
							<a href="blog-single.html">
								<img src="/images/slider/slider1.jpg" alt="" class="img-fluid">
							</a>
						</div>
						<div class="slider-post-content">
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Lifestyle</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">Tips for Taking a Long-term Trip</a></h3>
							<span class=" text-muted  text-capitalize">January 2, 2019</span>
						</div>
					</div>
				</div>
				<div class="slider-item">
					<div class="slider-item-content">
						<div class="post-thumb mb-4">
							<a href="blog-single.html">
								<img src="/images/slider/slider2.jpg" alt="" class="img-fluid">
							</a>
						</div>
						<div class="slider-post-content">
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Travel</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">Trip to California</a></h3>
							<span class=" text-muted  text-capitalize">September 15, 2019</span>
						</div>
					</div>
				</div>
				<div class="slider-item">
					<div class="slider-item-content">
						<div class="post-thumb mb-4">
							<a href="blog-single.html">
								<img src="/images/slider/slider3.jpg" alt="" class="img-fluid">
							</a>
						</div>
						<div class="slider-post-content">
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">weekends</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">Our Favorite Weekend Getaways</a></h3>
							<span class=" text-muted  text-capitalize">June 12, 2019</span>
						</div>
					</div>
				</div>
				<div class="slider-item">
					<div class="slider-item-content">
						<div class="post-thumb mb-4">
							<a href="blog-single.html">
								<img src="/images/slider/slider2.jpg" alt="" class="img-fluid">
							</a>
						</div>
						<div class="slider-post-content">
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Travel</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">Trip to California</a></h3>
							<span class=" text-muted  text-capitalize">September 15, 2019</span>
						</div>
					</div>
				</div>
				<div class="slider-item">
					<div class="slider-item-content">
						<div class="post-thumb mb-4">
							<a href="blog-single.html">
								<img src="/images/slider/slider3.jpg" alt="" class="img-fluid">
							</a>
						</div>
						<div class="slider-post-content">
							<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Travel</span>
							<h3 class="post-title mt-1"><a href="blog-single.html">Trip to California</a></h3>
							<span class=" text-muted  text-capitalize">September 15, 2019</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!--Slider Ends-->

AspNetMvcBlog/Blog.Web.Mvc/Views/Shared/_Subscribe.cshtml
<div class="row justify-content-center">
    <div class="col-lg-6">
        <div class="subscribe-footer text-center">
            <div class="form-group mb-0">
                <h2 class="mb-3">Subscribe Newsletter</h2>
                <p class="mb-4">Subscribe my Newsletter for new blog posts , tips and info.
                <p>
                    <div class="form-group form-row align-items-center mb-0">
                        <div class="col-sm-9">
                            <input type="email" class="form-control" placeholder="Email Address">
                        </div>
                        <div class="col-sm-3">
                            <a href="#" class="btn btn-dark ">Subscribe</a>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>